import "@/styles/globals.css";
import { Poppins } from 'next/font/google'
import { type Metadata } from "next";
import { TRPCReactProvider } from "@/trpc/react";

const poppins = Poppins({ weight: ["400", "500", "600", "700"], style: "normal", variable: "--poppins" });

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${poppins.variable}`}>
      <body>
        <TRPCReactProvider>{children}</TRPCReactProvider>

      </body>
    </html>
  );
}
